# Generated by Django 4.1.5 on 2023-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijava',
            name='odluka_donešena',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
