# Generated by Django 4.1.5 on 2023-01-31 04:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_prijava_dokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_predmeta', models.CharField(max_length=30, null=True)),
                ('ects', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(2)])),
                ('smjer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_site.smjer')),
            ],
        ),
    ]
